flow_name: "TGV"
model_name: "mpnn"
if_training: True
continue_training: False
model_path: None
tensorboard: True
saved_dir: "./checkpoint/"
output_dir: "./log/tensorboard/"
save_period: 2
seed: 0
# training args
training_type: "autoregressive" # "single_step"
epochs: 25
dataset:
  saved_folder: "/data1/FluidData/taylor_green_new"
  case_name: "Re_ReD"
  reduced_resolution: 1
  reduced_batch: 1
  norm_props: True
  stable_state_diff: 0.0001
  reshape_parameters: True
  multi_step_size: 3
dataloader:
  batch_size: 8
  num_workers: 1
  pin_memory: True
model:
  neighbors: 1
  delta_t: 0.1
  hidden_features: 128
  hidden_layers: 6
  n_params: 3
  var_id: 1 # u: 0, v: 1, ...
  spatial_dim: 2
optimizer:
  name: AdamW
  lr: 0.001
  weight_decay: 1.e-8
scheduler:
  name: "StepLR"
  step_size: 5
  gamma: 0.5