flow_name: 'NSCH'
model_name: "UNO"
if_training: True
continue_training: False
model_path: null
saved_dir: "./checkpoint/"
output_dir: "./output/"
save_period: 10
plot_interval: 1
# 训练相关参数
seed: 0
training_type: "autoregressive"
epochs: 100
# 数据集相关参数 
dataset:
  single_file: True
  saved_folder: "/home/data2/two_phase_flow/"
  reduced_resolution: 1
  reduced_batch: 1
  stable_state_diff: 0.001
  norm_props: True
  case_name: 'bc_ca_mob_phi_pre_re_uv0'
# dataloader相关参数
dataloader:
  train_batch_size: 128
  val_batch_size: 128
  test_batch_size: 1
  num_workers: 4
  pin_memory: False
# 模型相关参数
model:
  num_channels: 4
  width: 30
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 20
  gamma: 0.9