flow_name: 'cavity'
model_name: "LSM"
if_training: True
continue_training: False
model_path: null
saved_dir: "./checkpoint/"
output_dir: "./output/"
save_period: 10
plot_interval: 1
# 训练相关参数
seed: 0
training_type: "autoregressive"
epochs: 200
# 数据集相关参数 
dataset:
  single_file: True
  saved_folder: "/data1/FluidData/cavity_reduced/"
  reduced_resolution: 1
  reduced_batch: 1
  data_delta_time: 0.1
  delta_time: 0.1 
  stable_state_diff: 0.001
  norm_props: True
  norm_bc: True  
  case_name: 'ReD_bc_re'
  multi_step_size: 3
# dataloader相关参数
dataloader:
  train_batch_size: 128
  val_batch_size: 128
  test_batch_size: 1
  num_workers: 4
  pin_memory: False
# 模型相关参数
model:
  irregular_geo: False
  inputs_channel: 3
  outputs_channel: 3
  width: 32
  num_token: 4
  num_basis: 12
  patch_size: "4,4"
  padding: "0,0"
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 20
  gamma: 0.9
