flow_name: 'ircylinder'
model_name: "AutoDeepONet"
if_training: True
continue_training: False
model_path: null
saved_dir: "./checkpoint/"
output_dir: "./output/"
save_period: 10
plot_interval: 1
# 训练相关参数
seed: 0
training_type: "autoregressive"
epochs: 200
# 数据集相关参数 
dataset:
  single_file: True
  saved_folder: "/data1/FluidData/cylinder_reduced/"
  reduced_resolution: 1
  reduced_batch: 1
  norm_props: True
  case_name: 'irRE' # or irBC
  multi_step_size: 3
  reshape_parameters: False
# dataloader相关参数
dataloader:
  train_batch_size: 80
  val_batch_size: 80
  test_batch_size: 1
  num_workers: 4
  pin_memory: False
# 模型相关参数
model:
  irregular_geo: True       
  inputs_channel: 3
  outputs_channel: 3
  #num_points: 991  # or 1011, which should be determined on the fly.
  width: 100
  trunk_depth: 8
  branch_depth: 8
  act_fn: "relu"
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 5.e-4
  weight_decay: 1.e-7
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 20
  gamma: 0.9