flow_name: 'NSCH'
model_name: "AutoDeepONet"
if_training: True
continue_training: False
model_path: null
saved_dir: "./checkpoint/"
output_dir: "./output/"
save_period: 10
plot_interval: 1
# 训练相关参数
seed: 0
training_type: "autoregressive"
epochs: 200
# 数据集相关参数 
dataset:
  single_file: True
  saved_folder: "/data1/FluidData/two_phase_flow/"
  reduced_resolution: 1
  reduced_batch: 1
  stable_state_diff: 0.001
  norm_props: True
  case_name: 'ibc_phi_ca_mob_re_eps'
  multi_step_size: 3
  reshape_parameters: False
# dataloader相关参数
dataloader:
  train_batch_size: 128
  val_batch_size: 128
  test_batch_size: 1
  num_workers: 4
  pin_memory: False
# 模型相关参数
model:
  irregular_geo: False
  inputs_channel: 3
  outputs_channel: 3
  h: 66
  w: 66
  width: 100
  trunk_depth: 8
  branch_depth: 8
  act_fn: "relu"
# 优化器相关参数
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler相关参数
scheduler:
  name: "StepLR"
  step_size: 20
  gamma: 0.9