flow_name: "Darcy"
model_name: "gnot"
if_training: True
continue_training: False
model_path: None
tensorboard: True
saved_dir: "./checkpoint/"
output_dir: "./log/tensorboard/"
save_period: 5
seed: 0
# training args
training_type: "autoregressive" # "single_step"
epochs: 50
dataset:
  saved_folder: "/data1/FluidData/darcy"
  case_name: "PDEBench"
  reduced_resolution: 1
  reduced_batch: 1
dataloader:
  batch_size: 8
  num_workers: 1
  pin_memory: True
model:
  trunk_size: 3 # 2+num_case_params
  branch_sizes: [3] # space_dim+output_size
  space_dim: 2
  output_size: 1
  n_layers: 3 # the number of attention layers
  n_hidden: 96 # the number of feature dims
  n_head: 4 # the number of heads
  n_experts: 1 # the number of experts
  n_inner: 4
  mlp_layers: 3 # the number of layers in trunk mlp and output mlp
optimizer:
  name: AdamW
  lr: 0.001
  weight_decay: 0.00005
scheduler:
  name: "StepLR"
  step_size: 10
  gamma: 0.5